-- Run this in the Supabase SQL Editor.

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  quiz_id text not null,
  username text not null,
  score integer not null check (score >= 0),
  total_questions integer not null default 10,
  duration_seconds integer not null check (duration_seconds >= 0 and duration_seconds <= 60),
  timed_out boolean not null default false,
  answers jsonb not null default '[]'::jsonb,
  user_agent text
);

alter table public.quiz_results enable row level security;

drop policy if exists "Public can submit general quiz results" on public.quiz_results;

create policy "Public can submit general quiz results"
on public.quiz_results
for insert
to anon
with check (
  quiz_id = 'general-quiz-demo-2'
  and total_questions = 10
  and duration_seconds between 0 and 60
  and char_length(username) between 2 and 50
);

-- No public SELECT policy is created.
-- Results can be viewed inside the Supabase dashboard.
